['global config for FSRS4Anki']
w = [ 1.0, 1.0, 5.0, -0.5, -0.5, 0.2, 1.4, -0.12, 0.8, 2.0, -0.2, 0.2, 1.0 ]
requestRetention = 0.9
maximumInterval = 36500
easyBonus = 1.3
hardInterval = 1.2

['ALL::Learning::English::Reading']
w = [ 1.0, 1.0, 5.0, -0.5, -0.5, 0.2, 1.4, -0.12, 0.8, 2.0, -0.2, 0.2, 1.0 ]
requestRetention = 0.9
maximumInterval = 36500
easyBonus = 1.3
hardInterval = 1.2